### ISSUE TITLE
shutdown action handler causing issues

### ISSUE THREAD

**Issue by VivekManglani** [devgeniem/dustpress#16]
What is the purpose of the shutdown handler? 

`add_action( 'shutdown', [ $this, 'create_instance' ] );`

I'm using a third-party plugin, and somewhere in the plugin there is an **init** action handler which "die()"s the script if certain query parameters are found.

After the script dies, it runs the shutdown action hook which runs "create_instance".

**Comment by VivekManglani** [comment]
Oops! figured it out.

```
if ( ! function_exists('custom_autoload_conditions'))
{
	function custom_autoload_conditions($conditions)
	{
		return array_merge($conditions, [
			function () {
				return ! isset($_GET['cf_action']);
			}
		]);
	}

	add_filter('dustpress/want_autoload', 'custom_autoload_conditions');
}
```

**Comment by Nomafin** [comment]
The DustPress rendering is done in the shutdown hook, because it needs to be run after everything else and WordPress core doesn't have any other suitable hooks in the very end of the execution.

In some cases that can be a problem if there are such plugins that do stuff and die before normal execution would end. DustPress has a feature for that: in those cases you can add DustPress' `disable()` function in any hook or filter that is run in those cases, for example:

```
add_filter( 'wpseo_build_sitemap_post_type', array( dustpress(), 'disable' ), 1, 1 );
```

This filter would disable DustPress on Yoast's sitemap (this is included in core because the plugin is so common).

Apparently you found also the other way to do this, but I still commented this here because it could come in handy for someone else.
